config/routes.rb
Rails.application.routes.draw do
  get 'groups/index'
  get 'messages/index'
  root "kartes#toppage"
  # root "messages#index"
  
  devise_for :hosts, controllers: {
    sessions: 'hosts/sessions',
    passwords: 'hosts/passwords',
    registrations: 'hosts/registrations'
  }

  devise_for :casts, controllers: {
    sessions: 'casts/sessions',
    passwords: 'casts/passwords',
    registrations: 'casts/registrations'
  }

  devise_for :gests, controllers: {
    sessions: 'gests/sessions',
    passwords: 'gests/passwords',
    registrations: 'gests/registrations'
  }


  resources :hosts, only: [:index, :new, :create, :edit, :update] do
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end


  resources :casts, only: [:index, :new, :create, :edit, :update] do
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end


  resources :gests, only: [:index, :new, :create, :edit, :update] do
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end


  resources :kartes do
    resources :messages, only: [:index, :create]
    collection do
      get 'toppage'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/karte.rb
class Karte < ApplicationRecord
  has_many   :messages
  belongs_to :gest
  belongs_to :host, optional: true
  belongs_to :cast, optional: true
end

app/controllers/kartes_controller.rb
class KartesController < ApplicationController
  before_action :set_karte, only: [:show]

  def index

  end


  def new
    @karte = Karte.new
  end

  def create
    @karte = Karte.new(karte_params)
    if @karte.save!
      redirect_to karte_path(@karte)
    else
      render :new
    end
  end

  def toppage
  end

  def show
    @gests = Gest.all
    @message = Message.new
    @messages= @karte.messages.includes(:gest)
  end

  private

  def karte_params
    params.require(:karte).permit(:nickname, :gender_identities, :birthday, :age, :from, :consultation_content, :hearing1, :hearing2, :hearing3, :hearing4, :remarks).merge(gest_id: current_gest.id)
  end

  def set_karte
    @karte = Karte.find(params[:id])
  end
end

app/views/kartes/_main_chat.html.haml
.main-chat
  .main-chat__header
    .left-box
      .talk-name
        = "#{@karte.gest.nickname}とのtalk"
      .member-list
        %p Member:
        -# - @group.users.each do |user|
        -#   = user.name 
  
        -# = link_to edit_group_path(@group) do

    .edit-btn
      Edit

  .main-chat__messages
    -# = render @message
    .decoration
    - if @messages
      - @messages.each do |message|
        .main-chat__messages__message
          .data
            .talker
              - if message.host_id != nil
                = message.host.nickname
              - if message.cast_id != nil
                = message.cast.nickname
              - if message.gest_id != nil
                = message.gest.nickname

            .time
              = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
          .content
            = message.content

  .form
    = form_with(model: [@karte, @message], local: true) do |f|
      .new_message
        .input-box
          = f.text_field :content, class: 'input-box__message', placeholder: 'type a message' 
          .input-box__image
            = f.label :image, class: 'image' do
              = icon('fas', 'image' ,class: 'icon')
              = f.file_field :image, class: 'images'
        = f.submit 'send', class: 'send-btn'
    

app/views/kartes/_side_bar.html.haml
.side-bar
  .side-bar__header
    .side-bar__header__items
      .user
        = @karte.gest.nickname
      .icons
        = link_to new_gest_path do
          = icon('far','edit')
        = link_to edit_gest_path(@karte.gest.id) do
          = icon('fas','cog', class: 'icon')

  .side-bar__talk-list
    -# - current_gest.gests.each do |gest|
    .container
      .side-bar__talk-list__summary
        - @gests.each do |gest|
          .roster
            = link_to "#{gest.nickname}とのtalk", kartes_path(@karte)
          .latest-message
            -# = gests.show_last_message
            %p 最新のメッセージはありません

app/views/kartes/new.html.haml
.wrapper
  .karte-page
    = form_with(model: @karte, local: true) do |form|
      .header
        .header-bar
          .icon
            %i.fab.fa-elementor
          .name
            %hi Karte
      .main-space
        .hearing-top
          .q1
            .nickname
              %p ニックネーム
              .input-form
                = form.text_field :nickname, placeholder: 'からあげ'
            .gender_identities
              %p 性別
              .input-form
                = form.text_field :gender_identities, placeholder: '男性、女性、どちらでもない'
          .q2
            .birthday
              %p 生年月日
              .input-form
                = form.text_field :birthday, placeholder: '1990年04月05日'
            .age
              %p 年齢
              .input-form
                = form.text_field :age, placeholder: '30歳'
          .q3
            .from
              %p お住まいの地域
              .input-form
                = form.text_field :from, placeholder: '東京'
    
        .hearing-bottom
          .consultation_content
            %p お話ししたいこと
            .input-form
              = form.text_area :consultation_content, placeholder: '相談内容'
          .hearing1
            %p 現在服用中のお薬はありますか
            .input-form
              = form.radio_button :hearing1, "なし"
              = form.label :hearing1, "なし"
              = form.radio_button :hearing1, "はい"
              = form.label :hearing1, "はい"
          .hearing2
            %p 普段はよく眠れていますか
            .input-form
              = form.radio_button :hearing2, "いいえ"
              = form.label :hearing12, "いいえ"
              = form.radio_button :hearing2, "はい"
              = form.label :hearing2, "はい"
          .hearing3
            %p 女性の方のみ
            .input-form-comment
              %p 妊娠中ですか
              .input-form
                = form.radio_button :hearing3, "いいえ"
                = form.label :hearing3, "いいえ"
                = form.radio_button :hearing3, "はい"
                = form.label :hearing3, "はい"
          .hearing4
            %p 授乳中ですか
            .input-form
              = form.radio_button :hearing4, "いいえ"
              = form.label :hearing4, "いいえ"
              = form.radio_button :hearing4, "はい"
              = form.label :hearing4, "はい"
          .remarks
            %p その他気になることがございましたらお書きください
            .input-form
              = form.text_area :remarks, placeholder: '備考'
          .send-btn
            = button_tag "決定", type: 'submit'
          

app/views/kartes/show.html.haml
.m-wrapper
  = render "side_bar"
  = render "main_chat"

app/views/kartes/toppage.html.haml
.t-wrapper
  .top-page
    .top-page__header1
      .top-page__header2
        %h1 komorevigorden
      .top-page__header__category
        .tell
          %p お電話
          .tell__icon
            %i.fas.fa-phone-square
        .chat
          %p ご相談
          .chat__icon
            = link_to new_karte_path do
              %i.far.fa-comments

        .reservation
          %p 予約
          .reservation__icon
            %i.far.fa-calendar-alt
        .menu
          %p MENU
          .menu__icon
            %i.fas.fa-align-justify

    .top-page__main
      .signed_in
        - if gest_signed_in?
          = link_to "ログアウト", destroy_gest_session_path, method: :delete
        - else
          = link_to "ログイン", new_gest_session_path
          = link_to "新規登録", new_gest_registration_path
  
        - if cast_signed_in?
          = link_to "ログアウト", destroy_cast_session_path, method: :delete
        - else
          = link_to "ログイン", new_cast_session_path
          = link_to "新規登録", new_cast_registration_path
  
        - if host_signed_in?
          = link_to "ログアウト", destroy_host_session_path, method: :delete
        - else
          = link_to "ログイン", new_host_session_path
          = link_to "新規登録", new_host_registration_path
  
      .top-page__main__visual
        .name_container
          
        .top-page__main__visual__comment
          .komorebi-e
            %P komorebi
            .komorebi-j
              %p 木漏れ日
          .vigor-e
            %P vigor
            .vigor-j
              %p 活力、元気
          .den-e
            %p den
            .den-j
              %p 隠れ家
              
      .top-page__main__bar
        .picture
          = image_tag '/assets/1193651_s.jpg'
          = image_tag '/assets/3369870_s.jpg'
          = image_tag '/assets/1820829_s.jpg'
          = image_tag '/assets/3381902_s.jpg'
        
      .top-page__main__message
        %h1 ご挨拶
        %p 初めまして
        %p ここでは環境や立場が故に表立って声を上げづらい方達の、
        %p 本音を打ち明けられる場所、
        %p 相談できる場所です。
        %p 様々な事情を抱え、誰にも相談出来ずに一人で抱え込んでしまう人達が、
        %p 後悔しない選択ができるようにお手伝いできればと思っています。
        %p こちらでお伝えしたいことは
        %p ー自分で自分の価値を下げないでほしい
        %p ー自分に自信を持ち、等身大の自分を肯定してほしい
        %p ー現状は自分次第で変えることができると考えられるようになってほしい
        %p ー人に認めてもらう必要のない安心感、自信、自己肯定感を覚えてほしい
        %p この４つです。
        %p そのままのあなたのお話しをお聞かせください。

      .plus-image
        .top-page__main__news-event
          %h1 NEWS & EVENT
          %p 最新の投稿はありません
        .interior

      .top-page__main__schedule
        %table.biz-hour
          %tbody
            %tr
              %th 受付時間
              %th 月
              %th 火
              %th 水
              %th 木
              %th 金
              %th.sat 土
              %th.sun 日
            %tr
              %td 10:00〜12:00
              %td ●
              / 月
              %td ●
              / 火
              %td ●
              / 水
              %td ●
              / 木
              %td ●
              / 金
              %td ー
              / 土
              %td ー
              / 日
            %tr
              %td 21:00〜24:00
              %td ●
              / 月
              %td ー
              / 火
              %td ●
              / 水
              %td ー
              / 木
              %td ●
              / 金
              %td ー
              / 土
              %td ー
              / 日
        %p お休み / 土日祝

    .top-page__footer
      .top-page__footer__comment
        %p [月.水.金] 10:00 ~ 12:00 / 21:00 ~ 24:00
        %p [火.木] 10:00 ~ 12:00
        %p お休み / 土日祝
  
        .actions
          -# = form.submit "相談予約" , class:"btn"
      .top-page__footer__logo
        %h1 komorevigorden